name: Trips CI

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/**'
    - 'apis/trips/**'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/**'
    - 'apis/trips/**'

jobs:
  # The build and test workflow
  build-and-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: go build .
    - name: Run unit tests
      run: go test ./tests
    - name: Run integration tests
      run: go test
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Set image tag name
      run: echo "TAGNAME::$(date +'%Y-%m-%d'+github.run_id)" >> $GITHUB_ENV
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build the image
      run: |
        az acr build --image "devopsoh/api-trips:${TAGNAME}" --registry $ACRNAME --file Dockerfile .
    