name: Trips CI

on:
  push:
    branches:
    - main
    paths:
    - 'apis/trips/**'
  pull_request:
    branches:
    - main
    paths:
    - 'apis/trips/**'

jobs:
  # The build and test workflow
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: go build .
    - name: Run unit tests
      run: go test ./tests
    - name: Run integration tests
      run: go test
    