name: User Profile API CI/CD

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/user-profile.yaml'
    - 'apis/userprofile/**'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/user-profile.yaml'
    - 'apis/userprofile/**'

jobs:
  # The build and test workflow
  build-and-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/userprofile
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Installing dependencies
      run: npm ci
    - name: Building the app
      run: npm run build --if-present
    - name: Running tests
      run: npm test
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/userprofile
    environment: prod
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Set date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build the image
      run: |
        az acr build --image "devopsoh/api-userprofile:${{ steps.date.outputs.date }}${{ github.run_id }}" --image "devopsoh/api-userprofile:latest" --registry ${{ secrets.ACRNAME }} --file Dockerfile .
    