name: User-Java API CI/CD

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/user-java.yml'
    - 'apis/user-java/**'
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/user-java.yml'
    - 'apis/user-java/**'

jobs:
  # The build and test workflow
  build-and-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/user-java    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests
      run: mvn test
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/user-java
    environment: prod
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Set date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build the image
      run: |
        az acr build --image "devopsoh/api-user-java:${{ steps.date.outputs.date }}${{ github.run_id }}" --image "devopsoh/api-user-java:latest" --registry ${{ secrets.ACRNAME }} --file Dockerfile .
    